// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	"images/Unavngivet.png": string
	"images/Unavngivet2.png": string
	"images/noFilter.png": string
}

export = assets